FROM tomcat:8.5.15

MAINTAINER "YOUR NAME<YOUR EMAIL>"

RUN rm -rf /usr/local/tomcat/webapps/

ADD docker/postgresql-9.4.1212.jar /usr/local/tomcat/lib/
ADD target/blog.war /usr/local/tomcat/webapps/ROOT.war
